<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-07T17:09:30 IST" name="Default suite" finished-at="2023-04-07T17:09:30 IST" duration-ms="71">
    <groups>
      <group name="bvt">
        <method signature="SKIPTHETEST.btest2()[pri:1, instance:academicui.SKIPTHETEST@3d5c822d]" name="btest2" class="academicui.SKIPTHETEST"/>
      </group> <!-- bvt -->
      <group name="regression">
        <method signature="SKIPTHETEST.atest1R()[pri:1, instance:academicui.SKIPTHETEST@3d5c822d]" name="atest1R" class="academicui.SKIPTHETEST"/>
      </group> <!-- regression -->
    </groups>
    <test started-at="2023-04-07T17:09:30 IST" name="Default test" finished-at="2023-04-07T17:09:30 IST" duration-ms="71">
      <class name="academicui.SKIPTHETEST">
        <test-method signature="atest2R()[pri:0, instance:academicui.SKIPTHETEST@3d5c822d]" started-at="2023-04-07T17:09:30 IST" name="atest2R" finished-at="2023-04-07T17:09:30 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- atest2R -->
        <test-method signature="btest1()[pri:0, instance:academicui.SKIPTHETEST@3d5c822d]" started-at="2023-04-07T17:09:30 IST" name="btest1" finished-at="2023-04-07T17:09:30 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btest1 -->
        <test-method signature="btest3()[pri:0, instance:academicui.SKIPTHETEST@3d5c822d]" started-at="2023-04-07T17:09:30 IST" name="btest3" finished-at="2023-04-07T17:09:30 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btest3 -->
        <test-method signature="btest4()[pri:0, instance:academicui.SKIPTHETEST@3d5c822d]" started-at="2023-04-07T17:09:30 IST" name="btest4" finished-at="2023-04-07T17:09:30 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
Syntax error on token "throw", delete this token
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
Syntax error on token "throw", delete this token

at academicui.SKIPTHETEST.btest4(SKIPTHETEST.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btest4 -->
        <test-method signature="atest1R()[pri:1, instance:academicui.SKIPTHETEST@3d5c822d]" started-at="2023-04-07T17:09:30 IST" name="atest1R" finished-at="2023-04-07T17:09:30 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- atest1R -->
        <test-method signature="btest2()[pri:1, instance:academicui.SKIPTHETEST@3d5c822d]" started-at="2023-04-07T17:09:30 IST" name="btest2" finished-at="2023-04-07T17:09:30 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btest2 -->
      </class> <!-- academicui.SKIPTHETEST -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
